server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为True。单节点无所谓，集群必须设置为
    # true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 单机：defaultZone: http://localhost:7001/eureka
      # 以下是集群版配置
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
  # 修改服务中显示的主机名
  instance:
    instance-id: order80
    # 访问路径可以显示IP地址
    prefer-ip-address: true