# consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  # consul注册中心地址
  cloud:
    consul:
      host: 124.222.43.240
      port: 8500
      discovery:
        # hostname: 124.222.43.240
        service-name: ${spring.application.name}
        register-health-check: false # 不进行健康检测
