server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka

feign:
  client:
    config:
      default:
        # 设置feign客户端超时时间
        # 指的是建立连接后从服务器读取到可用资源所用的时间，单位：毫秒
        read-timeout: 5000
        # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
        connect-timeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    application.service.PaymentFeignService: debug